
services:

  mongodb:
    image: mongo

  traduxai.client:
    image: ${DOCKER_REGISTRY-}traduxaiclient
    build:
      context: .
      dockerfile: src/TraduxAI.Client/TraduxAI.Client/Dockerfile
  traduxai.server:
   image: ${DOCKER_REGISTRY-}traduxaiserver
   build:
      context: .
      dockerfile: src/TraduxAI.Server/TraduxAI.Server/Dockerfile