@TraduxAI.Server_HostAddress = http://localhost:5109

GET {{TraduxAI.Server_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{TraduxAI.Server_HostAddress}}/api/FileTranslate/Translate
Content-Type: application/json
Accept: application/json
{
  "filePath": "C:\\Users\\Admin\\testOCR.jpg",
  "sourceLanguage": "es",
  "targetLanguage": "en"
}

###
POST {{TraduxAI.Server_HostAddress}}/api/DocumentProcessing/ocr/image
Content-Type: application/json
Accept: application/json
{
    "base64Image":"iVBORw0KGgoAAAANSUhEUgAAAJYAAAB4CAYAAAD1z5c3AAAAOXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZSBDcmVhdGlvbiB0aW1lIDIwMjMtMDktMTdUMjE6NTI6NTYtMDQ6MDAq7+8xAAAAAElFTkSuQmCC"
}